### PR TITLE
Apple clon page

### PR DESCRIPTION
**Pull request by bertil291utn**
### I've made this checklist

- Hero section
   - navbar
   - text
- Main section (images)
- Footer

Please I'm requesting a code reviewing, thank you for the feedback 💻 🚀

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really great work! @bertil291utn 
All the work you've put into this is clearly visible, great job! :medal_military: Please consider my comment below, make the necessary change and request another review. I wish you all the best and see you at the very top :rocket: 

#### Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @bertil291utn :handshake: 

### Thank you for doing the changes requested by the previous reviewer, I think your use of backgrounds is ideal :star2: there are only a few more things to work on

## Page Structure

#### Hero background

- [x] Good job covering 100% of the screen width with the hero background but the position is still odd use percentages for the **background-position** selector of the hero background to make it look closer to the original

image

#### Bottom images

- [x] The bottom images should be bigger and take 100% of the screen width, also they are overlapping with the hero background so let's fix them

image

#### Footer

- [x] The footer looks good but with the changes requested above it might need to get adjusted to the page, please make sure that it looks proportional before requesting for a code review again

## OPTIONAL

[OPTIONAL] I strongly encourage the use of the `<main>` tag for the dominant content of the `<body>` of a document

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @bertil291utn  ,  You have done a great job with this project. :clap:

**Pull request merged**
